# Generated by Django 5.0.2 on 2024-03-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_2',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True),
        ),
    ]
