# Generated by Django 5.0.2 on 2024-03-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_phone_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_2',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
